@extends('layouts.app')
@section('title', 'Nuevo evento | Bienestar SENA')
@section('header-actions')<a href="{{ route('admin.dashboard') }}" class="rounded-lg bg-white/10 px-3 py-2 text-sm text-white">Volver al panel</a>@endsection
@section('content')
<div class="mx-auto max-w-3xl"><div class="mb-6"><span class="eyebrow text-xs font-bold uppercase text-[#648273]">Agenda institucional</span><h1 class="mt-2 text-3xl font-semibold">Crear evento</h1><p class="mt-2 text-sm text-[#71847a]">Diseña una actividad y define con precisión quién puede participar.</p></div>
@if($periodos->isEmpty())<div class="rounded-2xl border border-[#e7d39d] bg-[#fff8e4] p-5 text-sm text-[#7a5b11]">Primero debes crear un período de inscripción.</div>@else
<form class="space-y-6 rounded-2xl border border-[#d9e5dc] bg-white p-6 shadow-sm" method="POST" action="{{ route('admin.eventos.guardar') }}">@csrf
<div class="grid gap-5 md:grid-cols-2"><label class="text-sm font-medium">Período<select class="mt-2 w-full rounded-xl border border-[#cddbd1] bg-[#fbfdfb] p-3 outline-none focus:border-[#23734d]" name="periodo_id">@foreach($periodos as $periodo)<option value="{{ $periodo->id }}">{{ $periodo->nombre }}</option>@endforeach</select></label><label class="text-sm font-medium">Nombre<input class="mt-2 w-full rounded-xl border border-[#cddbd1] bg-[#fbfdfb] p-3 outline-none focus:border-[#23734d]" name="nombre" value="{{ old('nombre') }}" required></label><label class="text-sm font-medium md:col-span-2">Descripción<textarea class="mt-2 w-full rounded-xl border border-[#cddbd1] bg-[#fbfdfb] p-3 outline-none focus:border-[#23734d]" name="descripcion" rows="3">{{ old('descripcion') }}</textarea></label><label class="text-sm font-medium">Fecha<input class="mt-2 w-full rounded-xl border border-[#cddbd1] bg-[#fbfdfb] p-3 outline-none focus:border-[#23734d]" name="fecha_evento" type="date" value="{{ old('fecha_evento') }}" required></label><label class="text-sm font-medium">Lugar<input class="mt-2 w-full rounded-xl border border-[#cddbd1] bg-[#fbfdfb] p-3 outline-none focus:border-[#23734d]" name="lugar" value="{{ old('lugar') }}"></label><label class="text-sm font-medium">Cupo máximo<input class="mt-2 w-full rounded-xl border border-[#cddbd1] bg-[#fbfdfb] p-3 outline-none focus:border-[#23734d]" name="cupo_maximo" type="number" min="1" value="{{ old('cupo_maximo') }}"></label></div>
<div class="rounded-2xl bg-[#f8fbf8] p-5"><div class="mb-4"><span class="eyebrow text-xs font-bold uppercase text-[#648273]">Segmentación</span><h2 class="mt-2 text-lg font-semibold">Define la audiencia</h2><p class="mt-1 text-sm text-[#71847a]">Todos los criterios se aplican al mostrar e inscribir en el evento.</p></div><div class="grid gap-5 md:grid-cols-2"><label class="text-sm font-medium">Género<select class="mt-2 w-full rounded-xl border border-[#cddbd1] bg-white p-3 outline-none focus:border-[#23734d]" name="dirigido_a_genero"><option value="TODOS" @selected(old('dirigido_a_genero', 'TODOS') === 'TODOS')>Todos</option><option value="MASCULINO" @selected(old('dirigido_a_genero') === 'MASCULINO')>Hombres</option><option value="FEMENINO" @selected(old('dirigido_a_genero') === 'FEMENINO')>Mujeres</option></select></label><div></div><label class="text-sm font-medium">Edad mínima <span class="font-normal text-[#71847a]">(opcional)</span><input class="mt-2 w-full rounded-xl border border-[#cddbd1] bg-white p-3 outline-none focus:border-[#23734d]" name="edad_minima" type="number" min="0" max="120" value="{{ old('edad_minima') }}" placeholder="Ej. 18"></label><label class="text-sm font-medium">Edad máxima <span class="font-normal text-[#71847a]">(opcional)</span><input class="mt-2 w-full rounded-xl border border-[#cddbd1] bg-white p-3 outline-none focus:border-[#23734d]" name="edad_maxima" type="number" min="0" max="120" value="{{ old('edad_maxima') }}" placeholder="Ej. 35"></label></div><div class="mt-5 space-y-3"><label class="flex items-center gap-3 rounded-xl border border-[#d9e5dc] bg-white p-4 text-sm font-medium"><input name="requiere_ser_padre_madre" value="1" type="checkbox" @checked(old('requiere_ser_padre_madre')) class="h-4 w-4 rounded border-[#9dbbaa] text-[#1d6b3d]"> Solo padres o madres</label><label class="flex items-center gap-3 rounded-xl border border-[#d9e5dc] bg-white p-4 text-sm font-medium"><input name="requiere_familiar_a_cargo" value="1" type="checkbox" @checked(old('requiere_familiar_a_cargo')) class="h-4 w-4 rounded border-[#9dbbaa] text-[#1d6b3d]"> Personas con familiares a cargo</label></div></div>
<div class="flex justify-end gap-3 border-t border-[#edf2ee] pt-5"><a href="{{ route('admin.dashboard') }}" class="rounded-xl bg-[#f0f5ef] px-5 py-3 text-sm font-semibold text-[#426b53]">Cancelar</a><button class="rounded-xl bg-[#1d6b3d] px-5 py-3 text-sm font-semibold text-white hover:bg-[#155630]">Crear evento</button></div></form>@endif</div>@endsection
